name: Tests

on:
  push:
    paths:
      - '**/*.py' # only run workflow when source files changed
  pull_request:
    paths:
      - '**/*.py'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install torch==1.10.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
          pip install torch-scatter -f https://data.pyg.org/whl/torch-1.10.0+cpu.html
          pip install .

      - name: Run Tests
        run: |
          python -m pytest
